#!/bin/bash

mkdir -p ~/soft/addons-repos
mkdir -p ~/.config/blender/3.1/scripts/modules
mkdir -p ~/.config/blender/3.1/scripts/addons

cd ~/soft/addons-repos

git clone https://github.com/0djentd/emtk.git
git clone https://github.com/0djentd/modal_shortcuts.git
git clone https://github.com/0djentd/libemtk.git
git clone https://github.com/0djentd/class_variables_editor_ui.git

ln -s ~/soft/addons-repos/emtk/src                          ~/.config/blender/3.1/scripts/addons/emtk
ln -s ~/soft/addons-repos/modal_shortcuts/src               ~/.config/blender/3.1/scripts/modules/modal_shortcuts
ln -s ~/soft/addons-repos/libemtk/src                       ~/.config/blender/3.1/scripts/modules/libemtk
ln -s ~/soft/addons-repos/class_variables_editor_ui/src     ~/.config/blender/3.1/scripts/modules/class_variables_editor_ui
